# Generated by Django 5.2.7 on 2026-02-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empresa', 'Empresa'), ('empleado', 'Empleado')], default='empresa', max_length=20),
        ),
    ]
